import {
  FiActivity,
  FiBriefcase,
  FiCalendar,
  FiClock,
  FiCpu,
  FiCreditCard,
  FiFileText,
  FiHome,
  FiInbox,
  FiLayers,
  FiMapPin,
  FiPackage,
  FiUsers,
  FiUserCheck,
  FiUserX,
  FiDollarSign,
  FiBell,
  FiClipboard,
  FiHeart,
  FiGrid,
  FiShield,
} from 'react-icons/fi'

/**
 * Sidebar items.
 * - `link`: always visible main tab
 * - `group`: main tab with + ; children (subtabs) show only when expanded
 * - `featureKey`: when set, tenants only see the item if Super Admin enabled that permission
 */
export const NAV_ITEMS = [
  { type: 'link', to: '/', end: true, title: 'Home', icon: FiHome, needsTenant: false },
  {
    type: 'link',
    to: '/ops/venues',
    title: 'Venues',
    icon: FiMapPin,
    needsTenant: true,
    featureKey: 'venues',
  },
  {
    type: 'link',
    to: '/ops/services',
    title: 'Services',
    icon: FiBriefcase,
    needsTenant: true,
    featureKey: 'services',
  },
  {
    type: 'link',
    to: '/ops/resources',
    title: 'Resources',
    icon: FiGrid,
    needsTenant: true,
    featureKey: 'resources',
  },
  {
    type: 'link',
    to: '/ops/emr',
    title: 'EMR',
    icon: FiHeart,
    needsTenant: true,
    featureKey: 'emr',
  },
  {
    type: 'group',
    id: 'analytics',
    title: 'Analytics',
    icon: FiActivity,
    needsTenant: true,
    featureKey: 'analytics',
    children: [
      {
        to: '/ops/analytics/attendance-master',
        title: 'Attendance Master',
        icon: FiClipboard,
        needsTenant: true,
        featureKey: 'analytics',
      },
      {
        to: '/ops/analytics/reminders',
        title: 'Reminders',
        icon: FiBell,
        needsTenant: true,
        featureKey: 'analytics',
      },
      {
        to: '/ops/analytics/payment-master',
        title: 'Payment Master',
        icon: FiCreditCard,
        needsTenant: true,
        featureKey: 'analytics',
      },
      {
        to: '/ops/analytics/unmapped-payments',
        title: 'Unmapped Payments',
        icon: FiDollarSign,
        needsTenant: true,
        featureKey: 'analytics',
      },
    ],
  },
  {
    type: 'group',
    id: 'staff',
    title: 'Manage Staff',
    icon: FiUserCheck,
    needsTenant: true,
    children: [
      {
        to: '/ops/staff/employees',
        title: 'Employee Master',
        icon: FiUserCheck,
        needsTenant: true,
        featureKey: 'employees',
      },
      {
        to: '/ops/staff/attendance',
        title: 'Attendance',
        icon: FiClock,
        needsTenant: true,
        featureKey: 'attendance',
      },
      {
        to: '/ops/staff/payroll',
        title: 'Payroll',
        icon: FiFileText,
        needsTenant: true,
        featureKey: 'payroll',
      },
      {
        to: '/ops/staff/payouts',
        title: 'Staff Payouts',
        icon: FiDollarSign,
        needsTenant: true,
        featureKey: 'staff_payouts',
      },
      {
        to: '/ops/staff/for-hire',
        title: 'Staff for hire',
        icon: FiUsers,
        needsTenant: true,
        featureKey: 'staff_for_hire',
      },
    ],
  },
  {
    type: 'group',
    id: 'customer',
    title: 'Manage Customer',
    icon: FiUsers,
    needsTenant: true,
    children: [
      {
        to: '/ops/customers',
        title: 'Customer Master',
        icon: FiUsers,
        needsTenant: true,
        featureKey: 'patients',
      },
      {
        to: '/ops/bookings',
        title: 'Booking',
        icon: FiCalendar,
        needsTenant: true,
        featureKey: 'bookings',
      },
      {
        to: '/ops/customer-lobby',
        title: 'Lobby',
        icon: FiInbox,
        needsTenant: true,
        featureKey: 'customer_lobby',
      },
      {
        to: '/ops/invoices',
        title: 'Invoices',
        icon: FiFileText,
        needsTenant: true,
        featureKey: 'invoices',
      },
      {
        to: '/ops/payments',
        title: 'Payment',
        icon: FiCreditCard,
        needsTenant: true,
        featureKey: 'payments',
      },
    ],
  },
  {
    type: 'group',
    id: 'tenants',
    title: 'Manage Tenants',
    icon: FiLayers,
    needsTenant: false,
    superOnly: true,
    children: [
      { to: '/tenants', title: 'Tenants', icon: FiLayers, needsTenant: false, superOnly: true },
      { to: '/lobby', title: 'Lobby', icon: FiInbox, needsTenant: false, superOnly: true },
      {
        to: '/tenants/offboarded',
        title: 'Offboarded',
        icon: FiUserX,
        needsTenant: false,
        superOnly: true,
      },
    ],
  },
  {
    type: 'link',
    to: '/ops/location-packages',
    title: 'Location & Package',
    icon: FiPackage,
    needsTenant: true,
    featureKey: 'packages',
  },
  {
    type: 'link',
    to: '/ops/n8n-templates',
    title: 'N8N Templates',
    icon: FiCpu,
    needsTenant: true,
    featureKey: 'n8n_templates',
  },
  {
    type: 'link',
    to: '/platform/permissions',
    title: 'Permissions',
    icon: FiShield,
    needsTenant: false,
    superOnly: true,
  },
  {
    type: 'link',
    to: '/platform/analytics',
    title: 'Platform analytics',
    icon: FiActivity,
    needsTenant: false,
    superOnly: true,
  },
]

/** @deprecated use NAV_ITEMS */
export const NAV_SECTIONS = NAV_ITEMS
